webserver:
  port: 3000
  allowedOrigin:
    - 'http://YOUR_DOMAIN_HERE'
    - '/\.REGEXP\.com$/'

url: 
  frontend: "URL of your frontend website"
  backend: "URL of your backend server"

db:
  uri: "mongodb://localhost/consoleit"

auth:
  secret: 'consoleit' # Secret for SHA-256 and session

mailer:
  transport:
    host: "Your SMTP provider here"
    port: 25 
    auth: 
      user: "Your mail address here"
      pass: "Your password here"
  defaults:
    from: "Your title <Your email address>"
  tmpls:
    new_user:
      title: ConsoleiT 注册邮件
      file: new_user.html
    reset_passwd_request:
      title: ConsoleiT 密码重置请求
      file: reset_passwd_request.html
    reset_passwd:
      title: ConsoleiT 新密码
      file: reset_passwd.html
  images:
    # For images, we will automatically identify the type of the image based on its extension name
    # e.g.: image/svg_xml, image/jpg ...
    # You can explicitly pass the content type using option 'type'
    # Attention! Images without extension will potentially screw up the logic
    # If you insist in doing that, specify its content type here
    - key: console
      file: console.png
    - key: bjmun
      file: bjmun.png

# Developer options
develope:
  # Enable testing routes
  testing: true
